### ISSUE TITLE
Should some of this work go to ART and some of it go to TSV

### ISSUE THREAD

**Issue by afrind** [afrind/moqbof#1]
Should some of this work go to ART and some of it go to TSV? Or should we have one single effort that takes up both parts of what you're proposing?

**Comment by SpencerDawkins** [comment]
I agree that this matters, but this needs to take a back seat to the first three BOF goals. If we get through those three goals, we'll have succeeded beyond our wildest dreams. 

- it might be useful to add a new section/subsection as "Post-BoF Goals", and 
- put "determining existing working groups" and "determine appropriate area(s)" there. 

I can't speak for anyone on the IESG, but I'd expect that talking about technical considerations is an appropriate use of face-to-face-to-virtual-face time, and talking about administrative minutia is better handed to (the MOQ) mailing list.

I'm going to go through the other issues @afrind has created in this repo, and then start working on PRs.

**Comment by SpencerDawkins** [comment]
I'm linking this to #6 .
